### ISSUE TITLE
Chrome crashes during new EC('secp256k1')

### ISSUE THREAD

**Issue by niran** [indutny/elliptic#88] opened 2016-05-11 00:25 UTC
The crash occurs during the check at the end of the `PresetCurve` constructor, `assert(this.g.mul(this.n).isInfinity(), 'Invalid curve, G*N != O')` (https://github.com/indutny/elliptic/blob/master/lib/elliptic/curves.js#L22). The `_fixedNafMul` call inside of `mul` never makes it to the end of the function before the entire tab crashes ("Aw, Snap!") during the iteration of the loop when `i === 1`.

I'm using webpack 1.13.0 to use elliptic in the browser.

**Comment by indutny** [comment] 2016-05-11 03:45
May I ask you to share the generated page with us? Thank you!

**Comment by fanatid** [comment] 2016-05-11 03:48
@niran If you need only `secp256k1` you can use [cryptocoinjs/secp256k1-node](https://github.com/cryptocoinjs/secp256k1-node)
unfortunately this library also uses `elliptic` in browser by default.. but also has little optimized js version with entry point `js.js`, if it's not hard for you can you check this version?

**Comment by niran** [comment] 2016-05-11 17:12
This file crashes Chrome when included in a script tag: https://gist.github.com/5b3e26009e0a20847c2ce4678821b733

This was generated by feeding a file with `import * as blah from 'secp256k1/lib/elliptic';` into Babel and Webpack.

**Comment by indutny** [comment] 2016-05-11 23:50
@niran doesn't seem to crash for me. What Chrome version are you using? May I ask you to `step into (F11)` in debugger as far as possible, and let me know where it will crash?

**Comment by niran** [comment] 2016-05-12 04:11
Chrome Version 51.0.2704.36 beta (64-bit). Crashes even in an incognito window.

The closest I could narrow down the crash is in this call within `mul`: https://github.com/indutny/elliptic/blob/master/lib/elliptic/curve/base.js#L61-L69

**Comment by indutny** [comment] 2016-05-12 04:12
I'm inclined to say that this is a Chrome bug. Going to test it on beta in a bit to confirm it.

**Comment by indutny** [comment] 2016-05-12 04:32
Yeah, it is a bug in V8 indeed:

```
#
# Fatal error in ../../v8/src/compiler/representation-change.cc, line 541
# RepresentationChangerError: node #23227:Int32Mul of kRepWord32 (Integral32) cannot be changed to kRepFloat64
#
```

Filed the V8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=5006 . Going to leave this issue open for now, until they will resolve this.

**Comment by indutny** [comment] 2016-05-12 04:33
Needless to say, stable Chrome works just fine.

**Comment by niran** [comment] 2016-05-12 04:37
Thanks for your help!

**Comment by indutny** [comment] 2016-05-12 04:38
No problem. Particular function that V8 crashes on is `comb10MulTo` in bn.js . Will try to isolate the problem as far as I can to speed up the process of fixing this.

**Comment by fanatid** [comment] 2016-05-12 05:02
@indutny I tested next code with browserify (with bn.js from git master), all works fine:
```js
var BN = require('./lib/bn')
var n32 = new BN(new Buffer('ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff', 'hex'))
console.log(n32.mulTo(n32, new BN()))
```
https://gist.github.com/anonymous/d733b0042b99023d19e2583886f5a81b

**Comment by fanatid** [comment] 2016-05-12 05:07
I think this issue related with webpack, tests for [cryptocoinjs/secp256k1-node](https://github.com/cryptocoinjs/secp256k1-node) runned in chrome not fails..

**Comment by indutny** [comment] 2016-05-12 07:07
@fanatid Indeed the problem manifests itself only when using webpack. Browserify build appears to be working just fine.

Nevertheless, this is a bug in V8, and should be addressed.

**Comment by fanatid** [comment] 2016-05-12 07:10
@indutny I tested bundle from webpack and problem is really in `comb10MulTo`.. `smallMulTo` works fine.

**Comment by indutny** [comment] 2016-05-12 07:24
@fanatid the `comb10MulTo` does not have any problem :) The problem is in V8.

**Comment by dcousens** [comment] 2016-05-12 07:45
@indutny

> and **the code that is causing Chrome to crash** is really in `comb10MulTo`

Is what he meant :smiley:

**Comment by indutny** [comment] 2016-05-12 18:56
Looks like V8 has just fixed the issue.

**Comment by fanatid** [comment] 2016-05-12 19:00
@indutny what was the problem? new features for `Math.imul`?

**Comment by indutny** [comment] 2016-05-12 19:06
@fanatid the `Math.imul` was incorrectly generated.

**Comment by indutny** [comment] 2016-05-17 05:56
Should be fixed now.

**Closed by indutny** 2016-05-17 05:56 UTC
